---
title: "boosted"
output: html_document
---

```{r}
library(MASS)
library(e1071)
library(car)
library(caret)
library(pROC)
library(tidymodels)
library(themis)
library(xgboost)

source("cleandata.R")
source("confusionmatrix.R")
```

```{r}
diabetes_raw <- read.csv("data/diabetes_012_health_indicators_BRFSS2015.csv")
diabetes <- cleandata(diabetes_raw)
head(diabetes)
```

```{r}
diabetes |> count(Diabetes_012)
```

```{r}
rec <- recipe(Diabetes_012 ~ ., data = diabetes) |>
  step_downsample(Diabetes_012)

rec_prep <- prep(rec)

train <- bake(rec_prep, new_data = NULL)

train |> count(Diabetes_012)
```

```{r}
train_matrix <- model.matrix(Diabetes_012 ~ . - 1, data = train)
label <- train$Diabetes_012

xgb.model <- xgboost(
  x = train_matrix,
  y = label,
  objective = "multi:softprob",
  eval_metric = "mlogloss"
)
```

```{r}
test_matrix <- model.matrix(Diabetes_012 ~ . - 1, data = diabetes)
pred <- predict(xgb.model, newdata = test_matrix)
pred <- matrix(pred, ncol = 3, byrow = TRUE)
pred.class <- factor(max.col(pred) - 1, labels = c("NoDiabetes", "PreDiabetes", "Diabetes"))
```

```{r}
cm <- confusionMatrix(pred.class, diabetes$Diabetes_012) 
plot_cm(cm)
```

