---
title: "explore"
output: pdf_document
---

```{r}
set.seed(123)

library(MASS)
library(caret)
library(car)
library(pROC)
library(brant)

source("cleandata.R")
source("confusionmatrix.R")
source("partition.R")
source("eval.R")
```

```{r}
diabetes_raw <- read.csv("data/diabetes_012_health_indicators_BRFSS2015.csv")
diabetes <- cleandata(diabetes_raw)
head(diabetes)
```

```{r}
diabetes |> count(Diabetes_012) |> ggplot(aes(x = "", y = n, fill=Diabetes_012)) + 
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) + 
  theme_void() + 
  labs(fill = "Diabetes Status")
```

```{r}
split <- partition(diabetes, 0.8)
train <- split$train
test <- split$test

train |> count(Diabetes_012)
```

```{r}
#    1–4   = Young (roughly 18–34)
#    5–9   = Middle-aged (35–64)
#    10–13 = Older adults (65+)

diabetes |> count(Age3)
```

```{r}
model_polr <- polr(
  Diabetes_012 ~ 
  logBMI_c + Age3 + HighBP + HighChol + 
  Smoker + Stroke + HeartDiseaseorAttack + 
  HvyAlcoholConsump + AnyHealthcare + NoDocbcCost + GenHlth + DiffWalk + Sex + Income  +
  HighBP:HighChol,
  data = train,
  method = "logistic",
  Hess = TRUE
)
```

```{r}
#model_polr <- model_polr_stepBIC
summary(model_polr)
```

```{r}
pvalues <- function (model, threshold = 0.05) {
  coefs <- as.data.frame(coef(summary(model_polr)))
  pvals <- pnorm(abs(coefs[, "t value"]), lower.tail = FALSE) * 2
  significant <- if_else(pvals < threshold, "*", "")
  summary <- cbind(coefs, "p value" = pvals, "sig" = significant)
  return(summary)
}
```

```{r}
pvalues(model_polr, 0.01)
```

```{r}
pred <- predict(model_polr, newdata = test, type = "probs")

roc_no <- roc(response = ifelse(test$Diabetes_012 == "NoDiabetes", 1, 0),
              predictor = pred[, "NoDiabetes"],
              quiet = TRUE)

roc_pre <- roc(response = ifelse(test$Diabetes_012 == "PreDiabetes", 1, 0),
               predictor = pred[, "PreDiabetes"],
               quiet = TRUE)

roc_dia <- roc(response = ifelse(test$Diabetes_012 == "Diabetes", 1, 0),
               predictor = pred[, "Diabetes"],
               quiet = TRUE)

plot(roc_no, col = "blue", main = "One-vs-rest ROC Curves", legacy.axes = TRUE)
plot(roc_pre, col = "orange", add = TRUE)
plot(roc_dia, col = "red", add = TRUE)
legend("bottomright",
       legend = c("NoDiabetes", "PreDiabetes", "Diabetes"),
       col = c("blue", "orange", "red"),
       lwd = 2)

auc(roc_no); auc(roc_pre); auc(roc_dia)
```
```{r}
vif(model_polr)
```

```{r}
target <- 0.7
avail <- roc_pre$sensitivities
closest <- avail[which.min(abs(avail - target))]
coords(roc_pre, x = closest, input = "sensitivity", ret = c("threshold", "specificity", "sensitivity"))
```

```{r}
pred <- predict(model_polr, newdata = test, type = "probs")
predclass <- predict(model_polr, newdata = test, type = "class")
pred_df <- as.data.frame(pred)

t_pre <- 0.5
t_diab <- 0.3

cm <- create_cm(pred_df, t_pre, t_diab, test)
cm$table
plot_cm(cm, "Cumulative Logit Model Confusion Matrix")
```

```{r}
qwk_score(predclass, test$Diabetes_012)
mae_ord(pred, test$Diabetes_012)
```


```{r}
get_probs <- function(model, df_new, title = "") {
  vary_seq = seq(min(diabetes$BMI), max(diabetes$BMI), by = 0.5)
  df_new <- df_new[rep(1, length(vary_seq)), , drop = FALSE]
  df_new[["BMI"]] <- vary_seq
  
  df_new[["logBMI_c"]] <- (log(df_new[["BMI"]]) - mean(log(diabetes$BMI))) / sd(log(diabetes$BMI))

  
  probs <- cbind(df_new, predict(model, newdata = df_new, type = "probs"))

  probs_long <- probs |>
    pivot_longer(cols = c(NoDiabetes, PreDiabetes, Diabetes),
                 names_to = "Outcome",
                 values_to = "Probability")
  
  probs_long$Outcome <- factor(probs_long$Outcome, 
                               levels = c("NoDiabetes",
                                          "PreDiabetes",
                                          "Diabetes"))

  return(probs_long)
}

plot_probs <- function(probs, title = "") {
  p <- ggplot(probs, aes(x = BMI, y = Probability, color = Outcome)) +
    geom_line() +
    labs(title = title)
  return(p)
}
```

```{r}
template <- model_polr$model[1, , drop = FALSE]

template$Age3 <- factor("Young", levels = levels(model_polr$model$Age3)) 
template$HighBP <- factor(0, levels = levels(model_polr$model$HighBP)) # 0 no high BP
template$HighChol <- factor(0, levels = levels(model_polr$model$HighChol)) # 0 no high Chol
template$PhysActivity <- factor(0, levels = levels(model_polr$model$PhysActivity)) # 0 no phys ac
template$Smoker <- factor(0, levels = levels(model_polr$model$Smoker)) # 0 no smoker
template$Stroke <- factor(0, levels = levels(model_polr$model$Stroke)) # 0 no stroke
template$HeartDiseaseorAttack <- factor(1, levels = levels(model_polr$model$HeartDiseaseorAttack))#  0 no disease
template$Fruits <- factor(1, levels = levels(model_polr$model$Fruits)) # 0 no fruits
template$Veggies <- factor(1, levels = levels(model_polr$model$Veggies)) #0 no veg
template$HvyAlcoholConsump <- factor(0, levels = levels(model_polr$model$HvyAlcoholConsump)) # 0 no alcohol
template$AnyHealthcare <- factor(0, levels = levels(model_polr$model$Veggies)) # 0 no healthcare
template$NoDocbcCost <- factor(0, levels = levels(model_polr$model$NoDocbcCost)) # 0 no doctor cost
template$GenHlth <- factor(1, levels = levels(model_polr$model$GenHlth)) # 1-5 1 excellent
template$DiffWalk <- factor(1, levels = levels(model_polr$model$DiffWalk)) # 0 no hard time climbing
template$Sex <- factor(0, levels = levels(model_polr$model$Sex)) # 0 female
template$Income <- factor(1, levels = levels(model_polr$model$Income)) # 1-8, 1 poor
```

```{r}
template$Sex <- factor(0, levels = levels(model_polr$model$Sex))
probs <- get_probs(model_polr, template)
plot_probs(probs, "BMI vs Diabetes Probability (Healthy Female)")

template$Sex <- factor(1, levels = levels(model_polr$model$Sex))
probs <- get_probs(model_polr, template)
plot_probs(probs, "BMI vs Diabetes Probability (Healthy Male)")
```

```{r}
brant(model_polr)
```

```{r}
summary(model_polr)
```

```{r}
brant(model_polr)
```

```{r}
pred_bal_class <- predict(model_polr, newdata = test, type = "class")
cm <- confusionMatrix(pred_bal_class, test$Diabetes_012)
cm$overall
qwk_score(pred, test$Diabetes_012)
mae_ord(pred, test$Diabetes_012)
```

