---
title: "boosted"
output: html_document
---

```{r}
set.seed(123)

library(MASS)
library(caret)
library(xgboost)

source("../cleandata.R")
source("../partition.R")
source("../confusionmatrix.R")
source("../eval.R")
```

```{r}
diabetes_raw <- read.csv("../data/diabetes_012_health_indicators_BRFSS2015.csv")

diabetes <- cleandata(diabetes_raw)
head(diabetes)
```

```{r}
diabetes |> count(Diabetes_012)
```

```{r}
split <- partition(diabetes, 0.8)
train <- split$train
test <- split$test

train |> count(Diabetes_012)
```

```{r}
train_matrix <- model.matrix(Diabetes_012 ~ . - 1, data = train)
label <- train$Diabetes_012

xgb.model <- xgboost(
  x = train_matrix,
  y = label,
  objective = "multi:softprob",
  eval_metric = "mlogloss",
  nrounds = 500L
)
```

```{r}
test_matrix <- model.matrix(Diabetes_012 ~ . - 1, data = test)
pred <- predict(xgb.model, newdata = test_matrix)
pred <- matrix(pred, ncol = 3, byrow = TRUE)
pred.class <- factor(max.col(pred) - 1, labels = c("NoDiabetes", "PreDiabetes", "Diabetes"))
```

```{r}
cm <- confusionMatrix(pred.class, test$Diabetes_012) 
plot_cm(cm)
```
```{r}
pred <- predict(xgb.model, newdata = test_matrix, type = "class")
cm$overall
qwk_score(pred, test$Diabetes_012)
mae_ord(pred, test$Diabetes_012)
```

