---
title: "ordforest"
output: html_document
---

```{r}
set.seed(123)

library(caret)
library(ordinalForest)

source("../cleandata.R")
source("../confusionmatrix.R")
source("../partition.R")
source("../eval.R")
```

```{r}
diabetes_raw <- read.csv("../data/diabetes_012_health_indicators_BRFSS2015.csv")
diabetes <- cleandata(diabetes_raw)
head(diabetes)
```

```{r}
diabetes |> count(Diabetes_012)
```

```{r}
split <- partition(diabetes, 0.8)
train <- split$train
test <- split$test

train |> count(Diabetes_012)
```

```{r}
#of.model <- ordfor(depvar = "Diabetes_012", data = as.data.frame(train))
#save(of.model, file = "ordforest.RData")
```

```{r}
load("ordforest.RData")
```

```{r}
pred <- predict(of.model, newdata = test)
```

```{r}
cm <- confusionMatrix(pred$ypred, test$Diabetes_012) 
plot_cm(cm)
```

```{r}
pred_bal_class <- predict(model_polr, newdata = test, type = "class")
cm <- confusionMatrix(pred_bal_class, test$Diabetes_012)
cm$overall
qwk_score(pred$ypred, test$Diabetes_012)
mae_ord(pred$ypred, test$Diabetes_012)
```
